# Generated by Django 5.1.2 on 2024-11-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(default=1, help_text='Time required for the recipe in minutes'),
            preserve_default=False,
        ),
    ]
